[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = [
  'composer install --optimize-autoloader --no-dev'
]

[phases.build]
cmds = [
  'echo "Using pre-built assets"',
  'mkdir -p storage/app/public/user_photos',
  'chmod -R 775 storage'
]

[start]
cmd = 'rm -f public/storage; php artisan storage:link; ls -la public/ | grep storage; ls -la storage/app/ | grep public; php artisan serve --host=0.0.0.0 --port=$PORT'
